SiteVersion 1.3.0/feed/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'feed/login.html'}, name='login'),
    url(r'^login/redirect/$', login, {'template_name': 'feed/login_redirect.html'}, name='login_redirect'),
    url(r'^logout/$', logout, {'template_name': 'feed/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    
    url(r'^reset-password/$', password_reset, {'template_name': 'feed/reset_password.html', 
        'post_reset_redirect': 'feed:password_reset_done', 
        'email_template_name': 'feed/reset_password_email.html'}, 
        name='reset_password'),
    
    url(r'^reset-password/done/$', password_reset_done, 
        {'template_name': 'feed/reset_password_done.html'}, 
        name='password_reset_done'),
    
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'feed/reset_password_confirm.html', 
         'post_reset_redirect': 'feed:password_reset_complete'}, 
        name='password_reset_confirm'),
    
    url(r'^reset-password/complete/$', password_reset_complete, 
        {'template_name': 'feed/reset_password_complete.html'}, 
        name='password_reset_complete'),

    url(r'^blog/$', views.PostView.as_view(), name='blog'),
    
]

SiteVersion 1.3.0/robotpage/urls.py
#robotpage URL Configuration
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from robotpage import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.login_redirect, name="login_redirect"),
    url(r'^frc6324/', include('sponsors.urls', namespace='sponsors')),
    url(r'^feed/', include('feed.urls', namespace='feed')),
    url(r'^scouting/', include('scouting.urls', namespace='scouting')),

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SiteVersion 1.3.0/scouting/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    
    url(r'^scoutdata/$', views.ScoutView, name='scoutdata'),
    url(r'^scouttable/(?P<script>[\w-]+)/$', views.ScoutDetailView, name='teamdata'),
  	url(r'^scouttable/$', views.ScoutTableView, name='scouttable'),
    url(r'^scouttable/(?P<script>[\w-]+)/edit/$', views.ScoutEditView, name='editdata'),
    url(r'^events/(?P<slug>[\w-]+)/$', views.EventView, name='eventdetails'),
    url(r'^scouttable/addmatch$', views.MatchAddView, name='addmatch'),
	url(r'^years/$', views.YearView, name='year'),
	url(r'^events/$', views.EventView, name='event'),


]

SiteVersion 1.3.0/scouting/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# These are models for scouting data

class YearModel(models.Model):

    year = models.CharField(max_length=100, blank=False)
    game = models.CharField(max_length=100, blank=False)

    def __str__(self):
        return self.year

class EventModel(models.Model):

    name = models.CharField(max_length=100)
    slug = models.CharField(max_length = 100, db_index = True, unique = True)
    date = models.CharField(max_length=100, blank=False)
    location = models.CharField(max_length=100, blank=False)
    year = models.ForeignKey(YearModel, related_name='years')


    def __str__(self):
        return self.name

class ScoutData(models.Model):

    number = models.IntegerField(default=0, blank=True)
    name = models.CharField(max_length=100, db_index = True)
    script = models.CharField(max_length = 100, db_index = True, unique = True)
    #event = models.ForeignKey(EventModel, related_name='events')

    #Team Abilities
    autoLine = models.BooleanField(default=False)
    autoScale = models.BooleanField(default=False)
    autoSwitch = models.BooleanField(default=False)
    climb = models.BooleanField(default=False)
    scale = models.BooleanField(default=False)
    switch = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Team'
        verbose_name_plural = 'Teams'

    def __str__(self):
        return str(self.number)

class MatchData(models.Model):

    team = models.ForeignKey(ScoutData, related_name='teams')
    #event = models.ForeignKey(EventModel, related_name='events')

    #Match Data
    autoLine = models.BooleanField(default=False)
    cubesSwitch = models.IntegerField(default=0, blank=True)
    cubesExchange = models.IntegerField(default=0, blank=True)
    cubesScale = models.IntegerField(default=0, blank=True)
    canClimb = models.BooleanField(default=False)
    refNumber = models.IntegerField(default=1, blank=False)
    timeCube = models.FloatField(default=0, blank=False)
    timeClimb = models.FloatField(default=0, blank=False)
    timeSwitch = models.FloatField(default=0, blank=False)
    timeScale = models.FloatField(default=0, blank=False)
    matchWon = models.BooleanField(default=False)
    autoScale = models.BooleanField(default=False)
    autoSwitch = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Match Data'
        verbose_name_plural = 'Match Data'

    def __str__(self):
        return self.team.name

SiteVersion 1.3.0/scouting/forms.py
from django import forms
from django.utils.text import slugify
from .models import ScoutData, MatchData

class ScoutForm(forms.ModelForm):

    class Meta:
        model = ScoutData
        fields = (
            'name',
            'number',
            'autoLine',
            'autoSwitch',
            'autoScale',
            'climb',
            'scale',
            'switch',
        )

        labels = {
            'name': 'Team Name',
            'number': 'Team Number',
            'autoLine': 'Can cross auto line?',
            'autoSwitch': 'Can place a cube on switch during autonomous?',
            'autoScale': 'Can place a cube on scale during autonomous?',
            'climb': 'Can climb?',
            'scale': 'Can place a cube on scale?',
            'switch': 'Can place a cube on switch?',
        }

    def save(self):
        instance = super(ScoutForm, self).save(commit=False)
        instance.script = slugify(instance.name)
        instance.save()

        return instance

class MatchForm(forms.ModelForm):

    class Meta:
        model = MatchData
        fields = (
            'team',
            'autoLine',
            'cubesSwitch',
            'cubesExchange',
            'cubesScale',
            'canClimb',
            'timeCube',
            'timeClimb',
            'timeSwitch',
            'timeScale',
            'matchWon',
        )

        labels = {
            'autoLine': 'Crossed auto line?',
            'cubesSwitch': 'How many cubes were placed on the switch?',
            'cubesExchange': 'How many cubes were placed in the exchange?',
            'cubesScale': 'How many cubes were placed on the scale?',
            'canClimb': 'Did the robot climb?',
            'timeCube': 'About how much time did the robot spend on the exchange? (In minutes)',
            'timeClimb': 'About how much time did the robot spend climbing? (In minutes)',
            'timeSwitch': 'About how much time did the robot spend on the switches? (In minutes)',
            'timeScale': 'About how much time did the robot spend on the scale? (In minutes)',
            'matchWon': 'Did they win the match?',
        }

SiteVersion 1.3.0/scouting/views.py
from django.shortcuts import render, redirect, reverse
from django.utils.text import slugify
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse
from .forms import ScoutForm, MatchForm
from .models import (ScoutData,
                    MatchData,
                    YearModel,
                    EventModel)

# Create your views here.

def ScoutView(request):
    if request.method =='POST':
        form = ScoutForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('scouting:scouttable'))
    else:
        form = ScoutForm()

        args = {'form': form}
        return render(request, 'scouting/scoutdata.html', args)


def ScoutTableView(request):

    team = ScoutData.objects.all()
    args = {'team': team}

    return render(request, 'scouting/scouttable.html', args)

'''
ATENTION!!!

This view must change in order to accomadate new game types.

For questions, ask Massi

'''
def ScoutDetailView(request, script=None, *args, **kwargs): 
    
    team = ScoutData.objects.all()
    match = MatchData.objects.all()

    #Must define variables before referencing them
    timeClimb = None
    cubesSwitch = None
    cubesExchange = None
    cubesScale = None
    timeSwitch = None
    timeScale = None
    totalClimb = 0
    obj_autoLine = None
    obj_canClimb = None

    #Makes sure that the pie chart does not recieve a zero as an integer
    def dataIsZero(number):
        if number == 0:
            return 1
        else:
            return float(number)

    #Turns a boolean value to either 0 or 1
    def boolToInt(boolean):
        if boolean == False:
            return 0
        else:
            return 1
    
        
    qs = ScoutData.objects.filter(script__iexact=script.upper())
    if qs.exists() and qs.count() == 1:
        
        obj = qs.first()
                
        obj_init = obj
        obj_name = obj.name
        obj_number = obj.number
        obj_script = obj.script

        #Must define variables before referencing them
        reference = 1
        numberOfMatches = 0
        cubesExchange = 0
        cubesSwitch = 0
        cubesScale = 0
        timeSwitch = 0
        timeClimb = 0
        timeScale = 0
        totalSwitch = 0
        totalExchange = 0
        totalScale = 0
        totalWon = 0
        switchList = []
        scaleList = []
        exchangeList = []
        numberMatch = []

        for matchs in match:
            if matchs.team.name == obj_name:
                totalSwitch += matchs.cubesSwitch
                totalExchange += matchs.cubesExchange
                totalScale += matchs.cubesScale
                totalWon += boolToInt(matchs.matchWon)
                totalClimb += boolToInt(matchs.canClimb)

                cubesSwitch = matchs.cubesSwitch
                cubesExchange = matchs.cubesExchange
                cubesScale = matchs.cubesScale
                cubesSwitch = matchs.cubesSwitch
                cubesExchange = matchs.cubesExchange
                cubesScale = matchs.cubesScale
                obj_autoLine = matchs.autoLine
                obj_canClimb = matchs.canClimb
                timeSwitch += matchs.timeSwitch
                timeClimb += matchs.timeClimb
                timeScale += matchs.timeScale
                numberOfMatches += 1
        
        for matchs in match:
            if matchs.team.name == obj_name:
                switchList.append( matchs.cubesSwitch )
                scaleList.append( matchs.cubesScale )
                exchangeList.append( matchs.cubesExchange )
                numberMatch.append( reference + 1 )



        obj_cubesExchange = float(cubesExchange)
        obj_cubesSwitch = float(cubesSwitch)
        obj_cubesScale = float(cubesScale)
        percentSwitch = float(timeSwitch)/dataIsZero(numberOfMatches)/2.5*100
        percentScale = float(timeScale)/dataIsZero(numberOfMatches)/2.5*100
        percentClimb = float(timeClimb)/dataIsZero(numberOfMatches)/2.5*100
        percentWon = float(totalWon)/dataIsZero(numberOfMatches)
        avSwitch = float(totalSwitch)/dataIsZero(numberOfMatches)
        avScale = float(totalScale)/dataIsZero(numberOfMatches)
        avExchange = float(totalExchange)/dataIsZero(numberOfMatches)


            
    args = {'obj_name': obj_name,
            'obj_number': obj_number,
            'obj_cubesExchange': obj_cubesExchange,
            'obj_cubesSwitch': obj_cubesSwitch,
            'obj_cubesScale': obj_cubesScale,
            'obj_autoLine': obj_autoLine,
            'obj_canClimb': obj_canClimb,
            'obj_script': obj_script,
            'percentClimb': percentClimb,
            'percentScale': percentScale,
            'percentSwitch': percentSwitch,
            'percentWon': percentWon,
            'numberOfMatches': numberOfMatches,
            'numberMatch': numberMatch,
            'switchList': switchList,
            'scaleList': scaleList,
            'exchangeList': exchangeList,
            'avSwitch': avSwitch,
            'avScale': avScale,
            'avExchange': avExchange,
            'team': team,
            'match': match}
                
            
    return render(request, 'scouting/teamdata.html', args)

def ScoutEditView(request, script=None, *args, **kwargs):
    team = ScoutData.objects.all()
    qs = ScoutData.objects.filter(script__iexact=script.upper())

    obj_init = None
    obj_name = None
    if qs.exists() and qs.count() == 1:
        
        obj = qs.first()
        
        obj_init = obj
        obj_name = obj.name


    if request.method == 'POST':
        form = ScoutForm(request.POST, instance=obj)

        if form.is_valid():
            form.save()
            return redirect(reverse('scouting:scouttable'))
    else:
        form = ScoutForm(instance=obj)
        args = {'form': form,
                'obj_name': obj_name,
                'team': team}

        return render(request, 'scouting/scoutedit.html', args)


def MatchAddView(request):
    team = ScoutData.objects.all()

    if request.method == 'POST':
        form = MatchForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(reverse('scouting:scouttable'))
    else:
        form = MatchForm()
        args = {'form': form,
                'team': team}

        return render(request, 'scouting/addmatch.html', args)

def YearView(request):
    year = YearModel.objects.all()
    args = {'year': year}
    

    return render(request, 'scouting/years.html', args)

def EventView(request):

    event = EventModel.objects.all()
    args = {'event': event}

    return render(request, 'scouting/events.html', args)

SiteVersion 1.3.0/scouting/templates/scouting/scouttable.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}

<title>FRC 6324|Scouting Data</title>

{% endblock %}

{% block body %}


<div class="jumbotron">
  <div class="container">
    <div class='row'>
      <div class = "col-md-7">
        <h1 class="display-3 font">Scouting Data <i class="fa fa-users" aria-hidden="true"></i></i></h1>  
      </div>
      <div class = "col-md-3">
        <p>
          <a class="font btn btn-outline-primary btn-block" href="{% url 'scouting:scoutdata' %}" role="button">Add a Team</a>
        </p>
        <p>
          <a class="font btn btn-outline-primary btn-block" href="{% url 'scouting:addmatch' %}" role="button">Add a Match</a>
        </p>
      </div>
    </div>
  </div>
</div>


<div class="container"> 
  <div class="card-deck mb-3 text-center">
    {% for teams in team %}
    <div class="col-lg-4">
      <div class="card mb-4 box-shadow">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">#{{ teams.number }}</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">{{ teams.name }}</h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>AutoLine in Autonomous?: {{ teams.autoLine }}</li>
            <li>Switch in Autonomous?: {{ teams.autoSwitch }}</li>
            <li>Scale in Autonomous?: {{ teams.autoScale }}</li>
            <li>Can Climb?: {{ teams.climb }}</li>
          </ul>
          <a class="font btn btn-lg btn-block btn-outline-primary" href="/scouting/scouttable/{{ teams.script }}" role="button">Details</a>
        </div>
      </div>
    </div>
    {% endfor %}   
  </div>
</div> 



   


{% endblock %}

SiteVersion 1.3.0/scouting/templates/scouting/teamdata.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block head %}
<title>FRC 6324|{{ obj_name }}</title>
{% endblock %}


{% block body %}
<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="font nav-link" href="#">
              <span data-feather="file"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="font nav-link" href="/scouting/scouttable/{{ obj_script }}/edit">
              <i class="fa fa-file" aria-hidden="false"></i>
              Edit Team
            </a>
          </li>
          <li class="nav-item">
            <a class="font nav-link" href="{% url 'scouting:addmatch' %}">
              <i class="fa fa-plus" aria-hidden="false"></i>
              Add Match
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading font d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Other Teams</span>
          <a class="d-flex align-items-right text-muted" href="#">
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          {% for teams in team %}
          <li class="nav-item">
            <a class="font nav-link" href="/scouting/scouttable/{{ teams.script }}">
              {{ teams.name }}
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="font h1">#{{ obj_number }}: {{ obj_name }}</h1>
      </div>



      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="font h2">Cubes in Switch per Match</h1>
        <h1 class="font h3">Average: {{ avSwitch }} cubes per match.</h1>
      </div>
      <canvas class="my-4" id="SwitchChart" width="900" height="380"></canvas>



      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="font h2">Cubes in Scale per Match</h1>
        <h1 class="font h3">Average: {{ avScale }} cubes per match.</h1>
      </div>
      <canvas class="my-4" id="ScaleChart" width="900" height="380"></canvas>

      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="font h2">Cubes in Exchange per Match</h1>
        <h1 class="font h3">Average: {{ avExchange }} cubes per match.</h1>
      </div>
      <canvas class="my-4" id="ExchangeChart" width="900" height="380"></canvas>

      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="font h2">Time Spent Per Match</h1>
      </div>
      <canvas class="my-4" id="pieChart" width="900" height="380"></canvas>

      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="font h2">Match Outcomes</h1>
      </div>
      <canvas class="my-4" id="matchChart" width="900" height="380"></canvas>


      <h2 class="font">Team History</h2>
      <div class="table-responsive">
        <table class="font table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>Cubes in Switch</th>
              <th>Cubes in Scale</th>
              <th>Crossed Auto Line</th>
              <th>Did it Climb</th>
            </tr>
          </thead>
          <tbody>
            {% for matchs in match %}
            {% if matchs.team.name == obj_name %}
            <tr>
              <td>{{ obj_number }}</td>
              <td>{{ matchs.cubesSwitch }}</td>
              <td>{{ matchs.cubesScale }}</td>
              <td>{{ matchs.autoLine }}</td>
              <td>{{ matchs.canClimb }}</td>
            </tr>
            {% endif %}
            {% endfor %}
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>




{% endblock %}

{% block script %}

<script>
  var matches = [];
  var num;
  for (num = 1; num <= {{ numberOfMatches }}; num++) {
    matches.push("Match " + num); 
  }



  var ctx = document.getElementById("ScaleChart").getContext('2d');;
  var barChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: matches,
      datasets: [{
        data: {{ scaleList }},
        lineTension: 0,
        backgroundColor: 'transparent',
        borderColor: '#2A458A',
        borderWidth: 4,
        pointBackgroundColor: '#007bff'
      }]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true,
                //max: 100,
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>

    <script>
      var matches = [];
      var num;
      for (num = 1; num <= {{ numberOfMatches }}; num++) {
        matches.push("Match " + num); 
      }

      var ctx = document.getElementById("SwitchChart").getContext('2d');;
      var barChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: matches,
          datasets: [{
            data: {{ switchList }},
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#9cc4fd',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: true,
                //max: 100,
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
    <script>
      var matches = [];
      var num;
      for (num = 1; num <= {{ numberOfMatches }}; num++) {
        matches.push("Match " + num); 
      }

      var ctx = document.getElementById("ExchangeChart").getContext('2d');;
      var barChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: matches,
          datasets: [{
            data: {{ exchangeList }},
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#9cc4fd',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: true,
                //max: 100,
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>

    <script>
      var ctxP = document.getElementById("pieChart").getContext('2d');
      var pieChart = new Chart(ctxP, {
        type: 'pie',
        data: {
          labels: ["Time on Switch", "Time on Scale", "Time Climbing"],
          datasets: [
          {
            data: [{{ percentSwitch }}, {{ percentScale }}, {{ percentClimb }}],
            backgroundColor: ["#9cc4fd", "#2A458A", "#86b0ff"],
            hoverBackgroundColor: ["#9cc4fd", "#2A458A", "#86b0ff"]
          }
          ]
        },
        options: {
          responsive: true
        }    
      });
    </script>

    <script>
      
      var ctxP = document.getElementById("matchChart").getContext('2d');
      var pieChart = new Chart(ctxP, {
        type: 'pie',
        data: {
          labels: ["Matches Won", "Matches Lost"],
          datasets: [
          {
            data: [{{ percentWon }}, {{ numberOfMatches }}-{{ percentWon }}],
            backgroundColor: ["#9cc4fd", "#2A458A"],
            hoverBackgroundColor: ["#9cc4fd", "#2A458A"]
          }
          ]
        },
        options: {
          responsive: true
        }    
      });



    </script>

    <script>
      
      var ctxP = document.getElementById("matchChart").getContext('2d');
      var pieChart = new Chart(ctxP, {
        type: 'pie',
        data: {
          labels: ["Climbed", "Did Not Climb"],
          datasets: [
          {
            data: [{{ percentWon }}, {{ numberOfMatches }}-{{ percentWon }}],
            backgroundColor: ["#9cc4fd", "#2A458A"],
            hoverBackgroundColor: ["#9cc4fd", "#2A458A"]
          }
          ]
        },
        options: {
          responsive: true
        }    
      });

    </script>

    {% endblock %}

SiteVersion 1.3.0/scouting/templates/scouting/teams.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}

<title>FRC 6324|Scouting Data</title>

{% endblock %}

{% block body %}


<div class="jumbotron">
  <div class="container">
    <div class='row'>
      <div class = "col-md-7">
        <h1 class="display-3 font">Scouting Data <i class="fa fa-users" aria-hidden="true"></i></i></h1>  
      </div>
      <div class = "col-md-3">
        <p>
          <a class="font btn btn-outline-primary btn-block" href="{% url 'scouting:scoutdata' %}" role="button">Add a Team</a>
        </p>
        <p>
          <a class="font btn btn-outline-primary btn-block" href="{% url 'scouting:addmatch' %}" role="button">Add a Match</a>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="container"> 
  <div class="card-deck mb-3 text-center">

  {% for teams in team %}
    {% if teams.events.name == "first" %}

      <div class="col-lg-4">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">#{{ teams.number }}</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ teams.name }}</h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>AutoLine in Autonomous?: {{ teams.autoLine }}</li>
              <li>Switch in Autonomous?: {{ teams.autoSwitch }}</li>
              <li>Scale in Autonomous?: {{ teams.autoScale }}</li>
              <li>Can Climb?: {{ teams.climb }}</li>
            </ul>
            <a class="font btn btn-lg btn-block btn-outline-primary" href="/scouting/scouttable/{{ teams.script }}" role="button">Details</a>
          </div>
        </div>
      </div>
 </div>
</div> 
    
  {% endif %}
{% endfor %}


{% endblock %}

SiteVersion 1.3.0/scouting/templates/scouting/years.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}

<title>Scouting Data</title>

{% endblock %}

{% block body %}

<div class="jumbotron">
  <div class="container">
    <div class='row'>
      <div class = "col-md-7">
        <h1 class="display-3 font">Scouting Data <i class="fa fa-users" aria-hidden="true"></i></i></h1>  
      </div>
      <div class = "col-md-3">
        <p>
          <a class="font btn btn-outline-primary btn-block" href="{% url 'sponsors:scoutdata' %}" role="button">Add a Team</a>
        </p>
        <p>
          <a class="font btn btn-outline-primary btn-block" href="{% url 'sponsors:addmatch' %}" role="button">Add a Match</a>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="container"> 
  <div class="card-deck mb-3 text-center">
    {% for years in year %}
    <div class="col-lg-4">
      <div class="card mb-4 box-shadow">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">#{{ teams.number }}</h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">{{ years.year }}</h1>
          <ul class="list-unstyled mt-3 mb-4">
            <li>AutoLine in Autonomous?: {{ teams.autoLine }}</li>
            <li>Switch in Autonomous?: {{ teams.autoSwitch }}</li>
            <li>Scale in Autonomous?: {{ teams.autoScale }}</li>
            <li>Can Climb?: {{ teams.climb }}</li>
          </ul>
          <a class="font btn btn-lg btn-block btn-outline-primary" href="/frc6324/scouttable/{{ teams.script }}" role="button">Details</a>
        </div>
      </div>
    </div>
    {% endfor %}   
  </div>
</div> 



   


{% endblock %}