SiteVersion 1.1.0/feed/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete
)

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'feed/login.html'}, name='login'),
    url(r'^login/redirect/$', login, {'template_name': 'feed/login_redirect.html'}, name='login_redirect'),
    url(r'^logout/$', logout, {'template_name': 'feed/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    
    url(r'^reset-password/$', password_reset, {'template_name': 'feed/reset_password.html', 
        'post_reset_redirect': 'feed:password_reset_done', 
        'email_template_name': 'feed/reset_password_email.html'}, 
        name='reset_password'),
    
    url(r'^reset-password/done/$', password_reset_done, 
        {'template_name': 'feed/reset_password_done.html'}, 
        name='password_reset_done'),
    
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'feed/reset_password_confirm.html', 
         'post_reset_redirect': 'feed:password_reset_complete'}, 
        name='password_reset_confirm'),
    
    url(r'^reset-password/complete/$', password_reset_complete, 
        {'template_name': 'feed/reset_password_complete.html'}, 
        name='password_reset_complete'),

    url(r'^blog/$', views.PostView.as_view(), name='blog'),
    
]

SiteVersion 1.1.0/robotpage/urls.py
#robotpage URL Configuration
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from robotpage import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.login_redirect, name="login_redirect"),
    url(r'^frc6324/', include('sponsors.urls', namespace='sponsors')),
    url(r'^feed/', include('feed.urls', namespace='feed')),
    url(r'^scouting/', include('scouting.urls', namespace='scouting')),

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SiteVersion 1.1.0/scouting/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    
    url(r'^scoutdata/$', views.ScoutView, name='scoutdata'),
    url(r'^scouttable/(?P<script>[\w-]+)/$', views.ScoutDetailView, name='teamdata'),
  	url(r'^scouttable/$', views.ScoutTableView, name='scouttable'),
    url(r'^scouttable/(?P<script>[\w-]+)/edit/$', views.ScoutEditView, name='editdata'),
    url(r'^events/(?P<slug>[\w-]+)/$', views.EventView, name='eventdetails'),
    url(r'^scouttable/addmatch$', views.MatchAddView, name='addmatch'),
	url(r'^years/$', views.YearView, name='year'),
	url(r'^events/$', views.EventView, name='event'),


]

SiteVersion 1.1.0/sponsors/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^sponsors/$', views.SponsorView, name='sponsor_page'),
    url(r'^silver/$', views.SilverSponsorView, name='silver_sponsor_page'),
    url(r'^bronze/$', views.BronzeSponsorView, name='bronze_sponsor_page'),
    url(r'^gold/(?P<slug>[\w-]+)/$', views.SponsorDetailView, name='sponsor_detail'),
    url(r'^silver/(?P<slug>[\w-]+)/$', views.SponsorDetailView, name='sponsor_detail'),
    url(r'^bronze/(?P<slug>[\w-]+)/$', views.SponsorDetailView, name='sponsor_detail'),
    url(r'^aboutus/$', views.HistoryView, name='about_us'),
    url(r'^members/$', views.MemberView, name='members'),
    url(r'^become/$', views.BecomeView, name='become'),
    url(r'^community/$', views.CommunityView, name='community'),
    url(r'^contact/$', views.ContactView, name='contact'),
    
    
]

SiteVersion 1.1.0/sponsors/models.py
from __future__ import unicode_literals

from django.db import models

# These are models for site contents

class SponsorClassModel(models.Model):
    name = models.CharField(max_length = 200, db_index = True)
    shortcode = models.CharField(max_length = 200, db_index = True, unique = True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'class'
        verbose_name_plural = 'classes'
        
    def __str__(self):
        return self.name


class SponsorModel(models.Model):   
    
    category = models.ForeignKey(SponsorClassModel, related_name='sponsors')
    name = models.CharField(max_length =200, db_index = True)
    image = models.ImageField(upload_to='sponsor_image', blank=True)
    slug = models.CharField(max_length = 200, db_index = True, unique = True)

    description = models.TextField(blank = True)

    class Meta:
        verbose_name = 'Sponsor'
        verbose_name_plural = 'Sponsors'
    
   # def __str__(self):
	#   return self.name

class MemberModel(models.Model):

    student = models.CharField(max_length =200, db_index = True)
    last = models.CharField(max_length =200, db_index = True, default="")

    class Meta:
        ordering = ['last', 'student']
        verbose_name = 'Member'
        verbose_name_plural = 'Members'

    def __str__(self):
        return self.student


class StaffModel(models.Model):

    staff = models.CharField(max_length =200, db_index = True)
    last = models.CharField(max_length =200, db_index = True, default="")

    class Meta:
        ordering = ['last', 'staff']
        verbose_name = 'Staff'
        verbose_name_plural = 'Staff'

    def __str__(self):
        return self.staff

class Header(models.Model):

    title = models.CharField(max_length=100)
    button = models.CharField(max_length=20, blank = True)
    body = models.TextField(blank = True)
    url = models.URLField(blank = True)

    def __str__(self):
        return self.title

    
class CommunityBlock(models.Model):

    title = models.CharField(max_length=100)
    body = models.TextField(blank = True)
    image = models.ImageField(upload_to='sponsor_image', blank=True)
    place = models.BooleanField()

    class Meta:
        verbose_name = 'Community Block'
        verbose_name_plural = 'Community Blocks'

    def __str__(self):
        return self.title

class HistoryBlock(models.Model):

    title = models.CharField(max_length=100)
    body = models.TextField(blank = True)
    image = models.ImageField(upload_to='sponsor_image', blank=True)
    place = models.BooleanField()

    class Meta:
        verbose_name = 'History Block'
        verbose_name_plural = 'History Blocks'

    def __str__(self):
        return self.title


class ContactModel(models.Model):

    name = models.CharField(max_length=100, blank=False)
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return self.name

SiteVersion 1.1.0/sponsors/forms.py
from django import forms
from django.utils.text import slugify
from .models import ContactModel

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = (
            'name',
            'email',
            'message',
           
        )

SiteVersion 1.1.0/sponsors/views.py
from django.shortcuts import render, redirect, reverse
from django.utils.text import slugify
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse
from .forms import ContactForm
from .models import (SponsorModel,
                    SponsorClassModel,
                    MemberModel,
                    StaffModel,
                    Header,
                    CommunityBlock,
                    HistoryBlock)


# Create your views here.

def home(request):
    stuff = Header.objects.all()
    args = {'stuff': stuff}

    return render(request, 'sponsors/home.html', args)

def SponsorView(request):

    sponsor = SponsorModel.objects.all()
    args = {'sponsor': sponsor}
    

    return render(request, 'sponsors/sponsorpage.html', args)


def SilverSponsorView(request):

    sponsor = SponsorModel.objects.all()
    args = {'sponsor': sponsor}
    

    return render(request, 'sponsors/silversponsorpage.html', args)


def BronzeSponsorView(request):

    sponsor = SponsorModel.objects.all()
    args = {'sponsor': sponsor}
    

    return render(request, 'sponsors/bronzesponsorpage.html', args)


def HistoryView(request):

    model = HistoryBlock.objects.all()
    args = {'model': model}
    
    return render(request, 'sponsors/aboutus.html', args)

def MemberView(request):

    student = MemberModel.objects.all()
    staff = StaffModel.objects.all()
    args = {'staff': staff,
            'student': student}
    
    return render(request, 'sponsors/members.html', args)

def BecomeView(request):
    
    return render(request, 'sponsors/become.html', {})


def SponsorDetailView(request, slug=None, *args, **kwargs):
    
    obj_init = None
    obj_name = None
    obj_stock = None
    obj_info = None
    obj_price = None
    obj_img = None
        
    qs = SponsorModel.objects.filter(slug__iexact=slug.upper())
    if qs.exists() and qs.count() == 1:
        
        obj = qs.first()
                
        obj_init = obj
        obj_img = obj.image
        obj_info = obj.description
        obj_name = obj.name
            
    
            
    args = {'obj_name': obj_name,
            'obj_img': obj_img,
            'obj_info': obj_info}
                
            
    return render(request, 'sponsors/sponsordetail.html', args)


def CommunityView(request):

    model = CommunityBlock.objects.all()
    args = {'model': model}
    
    return render(request, 'sponsors/community.html', args)

def BecomeView(request):
    
    return render(request, 'sponsors/become.html', {})


def ContactView(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            #messages.success(request, "Thanks, we will reply as soon as possible!")
            form.save()
            return redirect(reverse('sponsors:home'))


    else:
        form = ContactForm()
        args = {'form': form}

    return render(request, 'sponsors/contact.html', args)

SiteVersion 1.1.0/sponsors/templates/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    
    {% include 'meta.html' %}
    
    {% include 'head_css.html' %}

    {% include 'styles.html' %}
    
    {% block head %}{% endblock %}
    
  </head>

  <body>

  	{% include 'navbar.html' %}
    
    {% block body %}{% endblock %}

    {% include 'footer.html' %}

    {% include 'javascript.html' %}

    {% block script %}{% endblock %}
    
  </body>
</html>

SiteVersion 1.1.0/sponsors/templates/footer.html
{% load static %}
 <div class="container">
    
      <center><img align="middle" class="img-responsive" src="{% static 'img/devil.png' %}"></center>
      
    </div>

<div class="container">
<hr>

<footer>
    <div>
	    	<span class="font">&copy; 2019 Salem High School Robotics</span> 
	    	<span style="float:right;" class="font">Site Version 1.1.0=</span>
		  </div>
</footer>
</div>

SiteVersion 1.1.0/sponsors/templates/head_css.html
{% load static %}

<!-- Bootstrap core CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<!-- Custom styles for this template -->
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/navbar-top.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/carousel.css' %}">
<link rel="stylesheet" href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/bg-inverse.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}" rel="stylesheet">
<script src="https://use.fontawesome.com/30acb62f12.js"></script>

SiteVersion 1.1.0/sponsors/templates/javascript.html
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% load static %}

<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="{% static 'js/jquery.min.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>

<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>

<script src="{% static 'js/popper.min.js' %}"></script>

<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/holder.min.js' %}"></script>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

<script src="{% static 'js/holder.min.js' %}"></script>

<script src="{% static 'js/Chart.min.js' %}"></script>

<script src="{% static 'js/feather.min.js' %}"></script>

    

	
    

SiteVersion 1.1.0/sponsors/templates/meta.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<meta http-equiv="X-UA-Compatible" content="IE=edge" /> 

SiteVersion 1.1.0/sponsors/templates/navbar.html
{% load static %}
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse navbar-expand-md">
      <a class="font navbar-brand" href="{% url 'sponsors:home' %}">
        The Blue Devils
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">

        <ul class="navbar-nav mr-auto">                       

          <li class="nav-item dropdown">
            <a class="font nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">About Us</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="font dropdown-item" href="{% url 'sponsors:members' %}">Team Members</a>
              <a class="font dropdown-item" href="{% url 'sponsors:community' %}">Our Community</a>
              <a class="font dropdown-item" href="{% url 'sponsors:about_us' %}">Our History</a>
            </div>
          </li>

          <li class="nav-item">
          <a class="font nav-link" href="{% url 'sponsors:sponsor_page' %}">Sponsors</a>
          </li>

          <li class="nav-item dropdown">
            <a class="font nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Contact Us</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="font dropdown-item" href="{% url 'sponsors:become' %}">Become a Sponsor</a>
              <a class="font dropdown-item" href="{% url 'sponsors:contact' %}">Contact Us</a>
            </div>
          </li>

          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="font nav-link" href="{% url 'feed:blog' %}">Feed</a>
          </li>

          {% endif %}

          </ul>

          <ul class="nav navbar-nav navbar-right">

          {% if user.is_authenticated %}

            <ul class="nav navbar-nav navbar-right">
              <li class="nav-item dropdown">
              <a class="font nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profile</a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="font dropdown-item" href="{% url 'feed:view_profile' %}">Profile Page</a>
                <a class="font dropdown-item" href="{% url 'feed:edit_profile' %}">Edit Profile</a>
                <a class="font dropdown-item" href="{% url 'feed:change_password' %}">Change Password</a>
                <a class="font dropdown-item" href="/admin/">Administration</a>
                <a class="font dropdown-item" href="{% url 'feed:logout' %}">Logout</a>
              </div>
              </li>
            </ul>

          <li class="nav-item">
            <a class="font nav-link" href="{% url 'scouting:scouttable' %}">Scouting</a>
          </li>

          <li class="nav-item">
            <a class="font nav-link" href="/scouting/scouttable/salem-blue-devils/">Our Team</a>
          </li>

            {% else %}
            
            <li class="nav-item">
            <a class="font nav-link" href="{% url 'feed:login' %}">Sign In</a>
          </li>

          <li class="nav-item">
            <a class="font nav-link" href="{% url 'feed:blog' %}">Feed</a>
          </li>

          {% endif %}
        </ul>
      </div>
    </nav>



  

SiteVersion 1.1.0/sponsors/templates/styles.html
<style>

.btn-twitter {
  color:#fff;
} 

.btn-facebook {
  color:#fff;
} 

.btn-youtube {
  color:#fff;
} 

.font{
  font-family:ubuntu; 
  
}


.titleFont{
	font-family:ubuntu;
}


.rowb {
  margin-top: 30px;
  margin-bottom: 30px
}

</style>